name: Build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Spotless Apply
        run: ./gradlew spotlessApply

      - name: Spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Detekt
        run: ./gradlew detekt --stacktrace

      - name: Ktlint
        run: ./gradlew ktlintCheck --stacktrace

      - name: Build Health
        run: ./gradlew buildHealth --build-cache --stacktrace

      - name: Unit Tests
        run: ./gradlew test --build-cache --stacktrace

      - name: Jacoco test report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"

      - name: Upload detekt report
        uses: actions/upload-artifact@v3
        with:
          name: detekt-report
          path: "${{ github.workspace }}/**/build/reports/detekt/detekt.html"
