name: Kotlin Algorithms CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  GRADLE_HOME: ${{ github.workspace }}/gradle-home

jobs:
  unit_tests:
    name: Spotless and unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Make checksum.sh executable
        run: chmod +x checksum.sh

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - name: Spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Detekt
        run: ./gradlew detekt --stacktrace

      - name: Ktlint
        run: ./gradlew ktlintCheck --stacktrace

      - name: Unit Tests
        run: ./gradlew test --build-cache --stacktrace

      - name: (Fail-only) Bundle the Unit Test report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r unit-test-report.zip

      - name: (Fail-only) Upload the Unit Test report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-error-report
          path: unit-test-report.zip

      - name: Jacoco test report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"
