name: Movies App CI

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx5120m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
      TERM: dumb
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make checksum.sh executable
        run: chmod +x checksum.sh

      - name: Make check.sh executable
        run: chmod +x check.sh

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run all checks
        run: ./gradlew :movies:detekt :movies:spotlessCheck :movies:lintDebug

      - name: Archive Lint results
        uses: actions/upload-artifact@v1
        with:
          name: lint-report.html
          path: movies/build/reports/lint-results-debug.html

  #      - name: Archive Test results
  #        uses: actions/upload-artifact@v1
  #        with:
  #          name: test-report.html
  #          path: movies/build/reports/tests/testDebugUnitTest/index.html

  detekt:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: -Xmx5120m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
      TERM: dumb
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make checksum.sh executable
        run: chmod +x checksum.sh

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Detekt
        run: ./gradlew detekt

      - name: Archive Detekt results
        uses: actions/upload-artifact@v1
        with:
          name: detekt-report.html
          path: movies/build/reports/detekt/detekt.html

  build:
    runs-on: ubuntu-latest
    needs: [check, detekt]
    env:
      JAVA_TOOL_OPTIONS: -Xmx5120m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process
      TERM: dumb
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Make checksum.sh executable
        run: chmod +x checksum.sh

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build APK
        run: ./gradlew :movies:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: movies-debug.apk
          path: movies/build/outputs/apk/debug/movies-debug.apk